//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.25 at 11:50:28 AM CEST 
//


package com.iso29481_part_2a.schemas._20110819;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MessageInTransactionTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageInTransactionTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ISO29481_Part_2A.com/schemas/20110819}elementType">
 *       &lt;sequence>
 *         &lt;element name="requiredNotify" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dateLaMu" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="userLaMu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="send" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initiatorToExecutor" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="openSecondaryTransactionsAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="firstMessage" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="message">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="previous" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageInTransactionType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageInTransactionTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transaction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transactionPhase" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionPhaseType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionPhaseTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="group" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}GroupType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}GroupTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appendixTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageInTransactionTypeType", propOrder = {
    "requiredNotify",
    "dateLaMu",
    "userLaMu",
    "received",
    "send",
    "state",
    "initiatorToExecutor",
    "openSecondaryTransactionsAllowed",
    "firstMessage",
    "message",
    "previous",
    "transaction",
    "transactionPhase",
    "group",
    "appendixTypes"
})
public class MessageInTransactionTypeType
    extends ElementType
{

    protected BigInteger requiredNotify;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateLaMu;
    protected String userLaMu;
    protected Boolean received;
    protected Boolean send;
    protected String state;
    protected Boolean initiatorToExecutor;
    protected Boolean openSecondaryTransactionsAllowed;
    protected Boolean firstMessage;
    @XmlElement(required = true)
    protected MessageInTransactionTypeType.Message message;
    protected MessageInTransactionTypeType.Previous previous;
    @XmlElement(required = true)
    protected MessageInTransactionTypeType.Transaction transaction;
    protected MessageInTransactionTypeType.TransactionPhase transactionPhase;
    protected MessageInTransactionTypeType.Group group;
    protected MessageInTransactionTypeType.AppendixTypes appendixTypes;

    /**
     * Gets the value of the requiredNotify property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequiredNotify() {
        return requiredNotify;
    }

    /**
     * Sets the value of the requiredNotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequiredNotify(BigInteger value) {
        this.requiredNotify = value;
    }

    /**
     * Gets the value of the dateLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLaMu() {
        return dateLaMu;
    }

    /**
     * Sets the value of the dateLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLaMu(XMLGregorianCalendar value) {
        this.dateLaMu = value;
    }

    /**
     * Gets the value of the userLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLaMu() {
        return userLaMu;
    }

    /**
     * Sets the value of the userLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLaMu(String value) {
        this.userLaMu = value;
    }

    /**
     * Gets the value of the received property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReceived() {
        return received;
    }

    /**
     * Sets the value of the received property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReceived(Boolean value) {
        this.received = value;
    }

    /**
     * Gets the value of the send property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSend() {
        return send;
    }

    /**
     * Sets the value of the send property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSend(Boolean value) {
        this.send = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the initiatorToExecutor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInitiatorToExecutor() {
        return initiatorToExecutor;
    }

    /**
     * Sets the value of the initiatorToExecutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInitiatorToExecutor(Boolean value) {
        this.initiatorToExecutor = value;
    }

    /**
     * Gets the value of the openSecondaryTransactionsAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOpenSecondaryTransactionsAllowed() {
        return openSecondaryTransactionsAllowed;
    }

    /**
     * Sets the value of the openSecondaryTransactionsAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOpenSecondaryTransactionsAllowed(Boolean value) {
        this.openSecondaryTransactionsAllowed = value;
    }

    /**
     * Gets the value of the firstMessage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFirstMessage() {
        return firstMessage;
    }

    /**
     * Sets the value of the firstMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFirstMessage(Boolean value) {
        this.firstMessage = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeType.Message }
     *     
     */
    public MessageInTransactionTypeType.Message getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeType.Message }
     *     
     */
    public void setMessage(MessageInTransactionTypeType.Message value) {
        this.message = value;
    }

    /**
     * Gets the value of the previous property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeType.Previous }
     *     
     */
    public MessageInTransactionTypeType.Previous getPrevious() {
        return previous;
    }

    /**
     * Sets the value of the previous property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeType.Previous }
     *     
     */
    public void setPrevious(MessageInTransactionTypeType.Previous value) {
        this.previous = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeType.Transaction }
     *     
     */
    public MessageInTransactionTypeType.Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeType.Transaction }
     *     
     */
    public void setTransaction(MessageInTransactionTypeType.Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the transactionPhase property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeType.TransactionPhase }
     *     
     */
    public MessageInTransactionTypeType.TransactionPhase getTransactionPhase() {
        return transactionPhase;
    }

    /**
     * Sets the value of the transactionPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeType.TransactionPhase }
     *     
     */
    public void setTransactionPhase(MessageInTransactionTypeType.TransactionPhase value) {
        this.transactionPhase = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeType.Group }
     *     
     */
    public MessageInTransactionTypeType.Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeType.Group }
     *     
     */
    public void setGroup(MessageInTransactionTypeType.Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the appendixTypes property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeType.AppendixTypes }
     *     
     */
    public MessageInTransactionTypeType.AppendixTypes getAppendixTypes() {
        return appendixTypes;
    }

    /**
     * Sets the value of the appendixTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeType.AppendixTypes }
     *     
     */
    public void setAppendixTypes(MessageInTransactionTypeType.AppendixTypes value) {
        this.appendixTypes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appendixTypeOrAppendixTypeRef"
    })
    public static class AppendixTypes {

        @XmlElements({
            @XmlElement(name = "AppendixType", type = AppendixTypeType.class),
            @XmlElement(name = "AppendixTypeRef", type = AppendixTypeTypeRef.class)
        })
        protected List<Object> appendixTypeOrAppendixTypeRef;

        /**
         * Gets the value of the appendixTypeOrAppendixTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the appendixTypeOrAppendixTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAppendixTypeOrAppendixTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppendixTypeType }
         * {@link AppendixTypeTypeRef }
         * 
         * 
         */
        public List<Object> getAppendixTypeOrAppendixTypeRef() {
            if (appendixTypeOrAppendixTypeRef == null) {
                appendixTypeOrAppendixTypeRef = new ArrayList<Object>();
            }
            return this.appendixTypeOrAppendixTypeRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}GroupType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}GroupTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groupType",
        "groupTypeRef"
    })
    public static class Group {

        @XmlElement(name = "GroupType")
        protected GroupTypeType groupType;
        @XmlElement(name = "GroupTypeRef")
        protected GroupTypeTypeRef groupTypeRef;

        /**
         * Gets the value of the groupType property.
         * 
         * @return
         *     possible object is
         *     {@link GroupTypeType }
         *     
         */
        public GroupTypeType getGroupType() {
            return groupType;
        }

        /**
         * Sets the value of the groupType property.
         * 
         * @param value
         *     allowed object is
         *     {@link GroupTypeType }
         *     
         */
        public void setGroupType(GroupTypeType value) {
            this.groupType = value;
        }

        /**
         * Gets the value of the groupTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link GroupTypeTypeRef }
         *     
         */
        public GroupTypeTypeRef getGroupTypeRef() {
            return groupTypeRef;
        }

        /**
         * Sets the value of the groupTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link GroupTypeTypeRef }
         *     
         */
        public void setGroupTypeRef(GroupTypeTypeRef value) {
            this.groupTypeRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageType",
        "messageTypeRef"
    })
    public static class Message {

        @XmlElement(name = "MessageType")
        protected MessageTypeType messageType;
        @XmlElement(name = "MessageTypeRef")
        protected MessageTypeTypeRef messageTypeRef;

        /**
         * Gets the value of the messageType property.
         * 
         * @return
         *     possible object is
         *     {@link MessageTypeType }
         *     
         */
        public MessageTypeType getMessageType() {
            return messageType;
        }

        /**
         * Sets the value of the messageType property.
         * 
         * @param value
         *     allowed object is
         *     {@link MessageTypeType }
         *     
         */
        public void setMessageType(MessageTypeType value) {
            this.messageType = value;
        }

        /**
         * Gets the value of the messageTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link MessageTypeTypeRef }
         *     
         */
        public MessageTypeTypeRef getMessageTypeRef() {
            return messageTypeRef;
        }

        /**
         * Sets the value of the messageTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link MessageTypeTypeRef }
         *     
         */
        public void setMessageTypeRef(MessageTypeTypeRef value) {
            this.messageTypeRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageInTransactionType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}MessageInTransactionTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageInTransactionTypeOrMessageInTransactionTypeRef"
    })
    public static class Previous {

        @XmlElements({
            @XmlElement(name = "MessageInTransactionType", type = MessageInTransactionTypeType.class),
            @XmlElement(name = "MessageInTransactionTypeRef", type = MessageInTransactionTypeTypeRef.class)
        })
        protected List<Object> messageInTransactionTypeOrMessageInTransactionTypeRef;

        /**
         * Gets the value of the messageInTransactionTypeOrMessageInTransactionTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the messageInTransactionTypeOrMessageInTransactionTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMessageInTransactionTypeOrMessageInTransactionTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MessageInTransactionTypeType }
         * {@link MessageInTransactionTypeTypeRef }
         * 
         * 
         */
        public List<Object> getMessageInTransactionTypeOrMessageInTransactionTypeRef() {
            if (messageInTransactionTypeOrMessageInTransactionTypeRef == null) {
                messageInTransactionTypeOrMessageInTransactionTypeRef = new ArrayList<Object>();
            }
            return this.messageInTransactionTypeOrMessageInTransactionTypeRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionType",
        "transactionTypeRef"
    })
    public static class Transaction {

        @XmlElement(name = "TransactionType")
        protected TransactionTypeType transactionType;
        @XmlElement(name = "TransactionTypeRef")
        protected TransactionTypeTypeRef transactionTypeRef;

        /**
         * Gets the value of the transactionType property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionTypeType }
         *     
         */
        public TransactionTypeType getTransactionType() {
            return transactionType;
        }

        /**
         * Sets the value of the transactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionTypeType }
         *     
         */
        public void setTransactionType(TransactionTypeType value) {
            this.transactionType = value;
        }

        /**
         * Gets the value of the transactionTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionTypeTypeRef }
         *     
         */
        public TransactionTypeTypeRef getTransactionTypeRef() {
            return transactionTypeRef;
        }

        /**
         * Sets the value of the transactionTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionTypeTypeRef }
         *     
         */
        public void setTransactionTypeRef(TransactionTypeTypeRef value) {
            this.transactionTypeRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionPhaseType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionPhaseTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionPhaseType",
        "transactionPhaseTypeRef"
    })
    public static class TransactionPhase {

        @XmlElement(name = "TransactionPhaseType")
        protected TransactionPhaseTypeType transactionPhaseType;
        @XmlElement(name = "TransactionPhaseTypeRef")
        protected TransactionPhaseTypeTypeRef transactionPhaseTypeRef;

        /**
         * Gets the value of the transactionPhaseType property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionPhaseTypeType }
         *     
         */
        public TransactionPhaseTypeType getTransactionPhaseType() {
            return transactionPhaseType;
        }

        /**
         * Sets the value of the transactionPhaseType property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionPhaseTypeType }
         *     
         */
        public void setTransactionPhaseType(TransactionPhaseTypeType value) {
            this.transactionPhaseType = value;
        }

        /**
         * Gets the value of the transactionPhaseTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionPhaseTypeTypeRef }
         *     
         */
        public TransactionPhaseTypeTypeRef getTransactionPhaseTypeRef() {
            return transactionPhaseTypeRef;
        }

        /**
         * Sets the value of the transactionPhaseTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionPhaseTypeTypeRef }
         *     
         */
        public void setTransactionPhaseTypeRef(TransactionPhaseTypeTypeRef value) {
            this.transactionPhaseTypeRef = value;
        }

    }

}
