//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.25 at 11:50:28 AM CEST 
//


package com.iso29481_part_2a.schemas._20110819;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TransactionTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ISO29481_Part_2A.com/schemas/20110819}elementType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateLaMu" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="userLaMu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="helpInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subTransactions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="initiator">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="executor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appendixTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionTypeType", propOrder = {
    "description",
    "startDate",
    "endDate",
    "state",
    "dateLaMu",
    "userLaMu",
    "language",
    "category",
    "helpInfo",
    "code",
    "result",
    "subTransactions",
    "initiator",
    "executor",
    "appendixTypes"
})
public class TransactionTypeType
    extends ElementType
{

    @XmlElement(required = true)
    protected String description;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    protected String state;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateLaMu;
    protected String userLaMu;
    protected String language;
    protected String category;
    protected String helpInfo;
    protected String code;
    protected String result;
    protected TransactionTypeType.SubTransactions subTransactions;
    @XmlElement(required = true)
    protected TransactionTypeType.Initiator initiator;
    @XmlElement(required = true)
    protected TransactionTypeType.Executor executor;
    protected TransactionTypeType.AppendixTypes appendixTypes;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the dateLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLaMu() {
        return dateLaMu;
    }

    /**
     * Sets the value of the dateLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLaMu(XMLGregorianCalendar value) {
        this.dateLaMu = value;
    }

    /**
     * Gets the value of the userLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLaMu() {
        return userLaMu;
    }

    /**
     * Sets the value of the userLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLaMu(String value) {
        this.userLaMu = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the helpInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpInfo() {
        return helpInfo;
    }

    /**
     * Sets the value of the helpInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpInfo(String value) {
        this.helpInfo = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the subTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeType.SubTransactions }
     *     
     */
    public TransactionTypeType.SubTransactions getSubTransactions() {
        return subTransactions;
    }

    /**
     * Sets the value of the subTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeType.SubTransactions }
     *     
     */
    public void setSubTransactions(TransactionTypeType.SubTransactions value) {
        this.subTransactions = value;
    }

    /**
     * Gets the value of the initiator property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeType.Initiator }
     *     
     */
    public TransactionTypeType.Initiator getInitiator() {
        return initiator;
    }

    /**
     * Sets the value of the initiator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeType.Initiator }
     *     
     */
    public void setInitiator(TransactionTypeType.Initiator value) {
        this.initiator = value;
    }

    /**
     * Gets the value of the executor property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeType.Executor }
     *     
     */
    public TransactionTypeType.Executor getExecutor() {
        return executor;
    }

    /**
     * Sets the value of the executor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeType.Executor }
     *     
     */
    public void setExecutor(TransactionTypeType.Executor value) {
        this.executor = value;
    }

    /**
     * Gets the value of the appendixTypes property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeType.AppendixTypes }
     *     
     */
    public TransactionTypeType.AppendixTypes getAppendixTypes() {
        return appendixTypes;
    }

    /**
     * Sets the value of the appendixTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeType.AppendixTypes }
     *     
     */
    public void setAppendixTypes(TransactionTypeType.AppendixTypes value) {
        this.appendixTypes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}AppendixTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appendixTypeOrAppendixTypeRef"
    })
    public static class AppendixTypes {

        @XmlElements({
            @XmlElement(name = "AppendixTypeRef", type = AppendixTypeTypeRef.class),
            @XmlElement(name = "AppendixType", type = AppendixTypeType.class)
        })
        protected List<Object> appendixTypeOrAppendixTypeRef;

        /**
         * Gets the value of the appendixTypeOrAppendixTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the appendixTypeOrAppendixTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAppendixTypeOrAppendixTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppendixTypeTypeRef }
         * {@link AppendixTypeType }
         * 
         * 
         */
        public List<Object> getAppendixTypeOrAppendixTypeRef() {
            if (appendixTypeOrAppendixTypeRef == null) {
                appendixTypeOrAppendixTypeRef = new ArrayList<Object>();
            }
            return this.appendixTypeOrAppendixTypeRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roleType",
        "roleTypeRef"
    })
    public static class Executor {

        @XmlElement(name = "RoleType")
        protected RoleTypeType roleType;
        @XmlElement(name = "RoleTypeRef")
        protected RoleTypeTypeRef roleTypeRef;

        /**
         * Gets the value of the roleType property.
         * 
         * @return
         *     possible object is
         *     {@link RoleTypeType }
         *     
         */
        public RoleTypeType getRoleType() {
            return roleType;
        }

        /**
         * Sets the value of the roleType property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoleTypeType }
         *     
         */
        public void setRoleType(RoleTypeType value) {
            this.roleType = value;
        }

        /**
         * Gets the value of the roleTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link RoleTypeTypeRef }
         *     
         */
        public RoleTypeTypeRef getRoleTypeRef() {
            return roleTypeRef;
        }

        /**
         * Sets the value of the roleTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoleTypeTypeRef }
         *     
         */
        public void setRoleTypeRef(RoleTypeTypeRef value) {
            this.roleTypeRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}RoleTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roleType",
        "roleTypeRef"
    })
    public static class Initiator {

        @XmlElement(name = "RoleType")
        protected RoleTypeType roleType;
        @XmlElement(name = "RoleTypeRef")
        protected RoleTypeTypeRef roleTypeRef;

        /**
         * Gets the value of the roleType property.
         * 
         * @return
         *     possible object is
         *     {@link RoleTypeType }
         *     
         */
        public RoleTypeType getRoleType() {
            return roleType;
        }

        /**
         * Sets the value of the roleType property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoleTypeType }
         *     
         */
        public void setRoleType(RoleTypeType value) {
            this.roleType = value;
        }

        /**
         * Gets the value of the roleTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link RoleTypeTypeRef }
         *     
         */
        public RoleTypeTypeRef getRoleTypeRef() {
            return roleTypeRef;
        }

        /**
         * Sets the value of the roleTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoleTypeTypeRef }
         *     
         */
        public void setRoleTypeRef(RoleTypeTypeRef value) {
            this.roleTypeRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}TransactionTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionTypeOrTransactionTypeRef"
    })
    public static class SubTransactions {

        @XmlElements({
            @XmlElement(name = "TransactionTypeRef", type = TransactionTypeTypeRef.class),
            @XmlElement(name = "TransactionType", type = TransactionTypeType.class)
        })
        protected List<Object> transactionTypeOrTransactionTypeRef;

        /**
         * Gets the value of the transactionTypeOrTransactionTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transactionTypeOrTransactionTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransactionTypeOrTransactionTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TransactionTypeTypeRef }
         * {@link TransactionTypeType }
         * 
         * 
         */
        public List<Object> getTransactionTypeOrTransactionTypeRef() {
            if (transactionTypeOrTransactionTypeRef == null) {
                transactionTypeOrTransactionTypeRef = new ArrayList<Object>();
            }
            return this.transactionTypeOrTransactionTypeRef;
        }

    }

}
