//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.25 at 11:50:28 AM CEST 
//


package com.iso29481_part_2a.schemas._20110819;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.iso29481_part_2a.schemas._20110819 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransactionTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "TransactionTypeRef");
    private final static QName _MessageInTransactionType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "MessageInTransactionType");
    private final static QName _ProjectType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "ProjectType");
    private final static QName _SimpleElementType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "SimpleElementType");
    private final static QName _ComplexElementTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "ComplexElementTypeRef");
    private final static QName _PersonType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "PersonType");
    private final static QName _RoleTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "RoleTypeRef");
    private final static QName _PersonTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "PersonTypeRef");
    private final static QName _AppendixType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "AppendixType");
    private final static QName _TransactionType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "TransactionType");
    private final static QName _ElementConditionRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "ElementConditionRef");
    private final static QName _UserDefinedTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "UserDefinedTypeRef");
    private final static QName _UserDefinedType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "UserDefinedType");
    private final static QName _GroupType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "GroupType");
    private final static QName _ProjectTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "ProjectTypeRef");
    private final static QName _MessageInTransactionTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "MessageInTransactionTypeRef");
    private final static QName _SimpleElementTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "SimpleElementTypeRef");
    private final static QName _MessageType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "MessageType");
    private final static QName _AppendixTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "AppendixTypeRef");
    private final static QName _RoleType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "RoleType");
    private final static QName _ComplexElementType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "ComplexElementType");
    private final static QName _ElementCondition_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "ElementCondition");
    private final static QName _GroupTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "GroupTypeRef");
    private final static QName _TransactionPhaseTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "TransactionPhaseTypeRef");
    private final static QName _MessageTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "MessageTypeRef");
    private final static QName _TransactionPhaseType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "TransactionPhaseType");
    private final static QName _OrganisationTypeRef_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "OrganisationTypeRef");
    private final static QName _OrganisationType_QNAME = new QName("http://www.ISO29481_Part_2A.com/schemas/20110819", "OrganisationType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.iso29481_part_2a.schemas._20110819
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransactionTypeType.Executor }
     * 
     */
    public TransactionTypeType.Executor createTransactionTypeTypeExecutor() {
        return new TransactionTypeType.Executor();
    }

    /**
     * Create an instance of {@link ISO29481Part2A }
     * 
     */
    public ISO29481Part2A createISO29481Part2A() {
        return new ISO29481Part2A();
    }

    /**
     * Create an instance of {@link AppendixTypeTypeRef }
     * 
     */
    public AppendixTypeTypeRef createAppendixTypeTypeRef() {
        return new AppendixTypeTypeRef();
    }

    /**
     * Create an instance of {@link ComplexElementTypeType }
     * 
     */
    public ComplexElementTypeType createComplexElementTypeType() {
        return new ComplexElementTypeType();
    }

    /**
     * Create an instance of {@link ProjectTypeType.ComplexElements }
     * 
     */
    public ProjectTypeType.ComplexElements createProjectTypeTypeComplexElements() {
        return new ProjectTypeType.ComplexElements();
    }

    /**
     * Create an instance of {@link MessageTypeType.AppendixTypes }
     * 
     */
    public MessageTypeType.AppendixTypes createMessageTypeTypeAppendixTypes() {
        return new MessageTypeType.AppendixTypes();
    }

    /**
     * Create an instance of {@link SimpleElementTypeType.UserDefinedType }
     * 
     */
    public SimpleElementTypeType.UserDefinedType createSimpleElementTypeTypeUserDefinedType() {
        return new SimpleElementTypeType.UserDefinedType();
    }

    /**
     * Create an instance of {@link PersonTypeType }
     * 
     */
    public PersonTypeType createPersonTypeType() {
        return new PersonTypeType();
    }

    /**
     * Create an instance of {@link ComplexElementTypeType.SimpleElements }
     * 
     */
    public ComplexElementTypeType.SimpleElements createComplexElementTypeTypeSimpleElements() {
        return new ComplexElementTypeType.SimpleElements();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeTypeRef }
     * 
     */
    public MessageInTransactionTypeTypeRef createMessageInTransactionTypeTypeRef() {
        return new MessageInTransactionTypeTypeRef();
    }

    /**
     * Create an instance of {@link ElementTypeRef }
     * 
     */
    public ElementTypeRef createElementTypeRef() {
        return new ElementTypeRef();
    }

    /**
     * Create an instance of {@link ElementConditionType.SimpleElement }
     * 
     */
    public ElementConditionType.SimpleElement createElementConditionTypeSimpleElement() {
        return new ElementConditionType.SimpleElement();
    }

    /**
     * Create an instance of {@link GroupTypeType }
     * 
     */
    public GroupTypeType createGroupTypeType() {
        return new GroupTypeType();
    }

    /**
     * Create an instance of {@link SimpleElementTypeTypeRef }
     * 
     */
    public SimpleElementTypeTypeRef createSimpleElementTypeTypeRef() {
        return new SimpleElementTypeTypeRef();
    }

    /**
     * Create an instance of {@link MessageTypeType }
     * 
     */
    public MessageTypeType createMessageTypeType() {
        return new MessageTypeType();
    }

    /**
     * Create an instance of {@link RoleTypeType }
     * 
     */
    public RoleTypeType createRoleTypeType() {
        return new RoleTypeType();
    }

    /**
     * Create an instance of {@link ElementConditionType.ComplexElement }
     * 
     */
    public ElementConditionType.ComplexElement createElementConditionTypeComplexElement() {
        return new ElementConditionType.ComplexElement();
    }

    /**
     * Create an instance of {@link ProjectTypeType }
     * 
     */
    public ProjectTypeType createProjectTypeType() {
        return new ProjectTypeType();
    }

    /**
     * Create an instance of {@link AppendixTypeType }
     * 
     */
    public AppendixTypeType createAppendixTypeType() {
        return new AppendixTypeType();
    }

    /**
     * Create an instance of {@link ComplexElementTypeTypeRef }
     * 
     */
    public ComplexElementTypeTypeRef createComplexElementTypeTypeRef() {
        return new ComplexElementTypeTypeRef();
    }

    /**
     * Create an instance of {@link MessageTypeType.ComplexElements }
     * 
     */
    public MessageTypeType.ComplexElements createMessageTypeTypeComplexElements() {
        return new MessageTypeType.ComplexElements();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeType.Message }
     * 
     */
    public MessageInTransactionTypeType.Message createMessageInTransactionTypeTypeMessage() {
        return new MessageInTransactionTypeType.Message();
    }

    /**
     * Create an instance of {@link ElementConditionType.MessageInTransaction }
     * 
     */
    public ElementConditionType.MessageInTransaction createElementConditionTypeMessageInTransaction() {
        return new ElementConditionType.MessageInTransaction();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeType.Previous }
     * 
     */
    public MessageInTransactionTypeType.Previous createMessageInTransactionTypeTypePrevious() {
        return new MessageInTransactionTypeType.Previous();
    }

    /**
     * Create an instance of {@link OrganisationTypeTypeRef }
     * 
     */
    public OrganisationTypeTypeRef createOrganisationTypeTypeRef() {
        return new OrganisationTypeTypeRef();
    }

    /**
     * Create an instance of {@link ElementConditionType }
     * 
     */
    public ElementConditionType createElementConditionType() {
        return new ElementConditionType();
    }

    /**
     * Create an instance of {@link PersonTypeTypeRef }
     * 
     */
    public PersonTypeTypeRef createPersonTypeTypeRef() {
        return new PersonTypeTypeRef();
    }

    /**
     * Create an instance of {@link TransactionTypeTypeRef }
     * 
     */
    public TransactionTypeTypeRef createTransactionTypeTypeRef() {
        return new TransactionTypeTypeRef();
    }

    /**
     * Create an instance of {@link AppendixTypeType.ComplexElements }
     * 
     */
    public AppendixTypeType.ComplexElements createAppendixTypeTypeComplexElements() {
        return new AppendixTypeType.ComplexElements();
    }

    /**
     * Create an instance of {@link TransactionPhaseTypeTypeRef }
     * 
     */
    public TransactionPhaseTypeTypeRef createTransactionPhaseTypeTypeRef() {
        return new TransactionPhaseTypeTypeRef();
    }

    /**
     * Create an instance of {@link TransactionTypeType.Initiator }
     * 
     */
    public TransactionTypeType.Initiator createTransactionTypeTypeInitiator() {
        return new TransactionTypeType.Initiator();
    }

    /**
     * Create an instance of {@link SimpleElementTypeType }
     * 
     */
    public SimpleElementTypeType createSimpleElementTypeType() {
        return new SimpleElementTypeType();
    }

    /**
     * Create an instance of {@link ComplexElementTypeType.ComplexElements }
     * 
     */
    public ComplexElementTypeType.ComplexElements createComplexElementTypeTypeComplexElements() {
        return new ComplexElementTypeType.ComplexElements();
    }

    /**
     * Create an instance of {@link ElementType }
     * 
     */
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeType.AppendixTypes }
     * 
     */
    public MessageInTransactionTypeType.AppendixTypes createMessageInTransactionTypeTypeAppendixTypes() {
        return new MessageInTransactionTypeType.AppendixTypes();
    }

    /**
     * Create an instance of {@link TransactionTypeType.SubTransactions }
     * 
     */
    public TransactionTypeType.SubTransactions createTransactionTypeTypeSubTransactions() {
        return new TransactionTypeType.SubTransactions();
    }

    /**
     * Create an instance of {@link RoleTypeTypeRef }
     * 
     */
    public RoleTypeTypeRef createRoleTypeTypeRef() {
        return new RoleTypeTypeRef();
    }

    /**
     * Create an instance of {@link ProjectTypeTypeRef }
     * 
     */
    public ProjectTypeTypeRef createProjectTypeTypeRef() {
        return new ProjectTypeTypeRef();
    }

    /**
     * Create an instance of {@link TransactionTypeType.AppendixTypes }
     * 
     */
    public TransactionTypeType.AppendixTypes createTransactionTypeTypeAppendixTypes() {
        return new TransactionTypeType.AppendixTypes();
    }

    /**
     * Create an instance of {@link UserDefinedTypeTypeRef }
     * 
     */
    public UserDefinedTypeTypeRef createUserDefinedTypeTypeRef() {
        return new UserDefinedTypeTypeRef();
    }

    /**
     * Create an instance of {@link PersonTypeType.ComplexElements }
     * 
     */
    public PersonTypeType.ComplexElements createPersonTypeTypeComplexElements() {
        return new PersonTypeType.ComplexElements();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeType.Transaction }
     * 
     */
    public MessageInTransactionTypeType.Transaction createMessageInTransactionTypeTypeTransaction() {
        return new MessageInTransactionTypeType.Transaction();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeType.TransactionPhase }
     * 
     */
    public MessageInTransactionTypeType.TransactionPhase createMessageInTransactionTypeTypeTransactionPhase() {
        return new MessageInTransactionTypeType.TransactionPhase();
    }

    /**
     * Create an instance of {@link ElementConditionTypeRef }
     * 
     */
    public ElementConditionTypeRef createElementConditionTypeRef() {
        return new ElementConditionTypeRef();
    }

    /**
     * Create an instance of {@link MessageTypeTypeRef }
     * 
     */
    public MessageTypeTypeRef createMessageTypeTypeRef() {
        return new MessageTypeTypeRef();
    }

    /**
     * Create an instance of {@link UserDefinedTypeType }
     * 
     */
    public UserDefinedTypeType createUserDefinedTypeType() {
        return new UserDefinedTypeType();
    }

    /**
     * Create an instance of {@link TransactionPhaseTypeType }
     * 
     */
    public TransactionPhaseTypeType createTransactionPhaseTypeType() {
        return new TransactionPhaseTypeType();
    }

    /**
     * Create an instance of {@link GroupTypeTypeRef }
     * 
     */
    public GroupTypeTypeRef createGroupTypeTypeRef() {
        return new GroupTypeTypeRef();
    }

    /**
     * Create an instance of {@link OrganisationTypeType.ComplexElements }
     * 
     */
    public OrganisationTypeType.ComplexElements createOrganisationTypeTypeComplexElements() {
        return new OrganisationTypeType.ComplexElements();
    }

    /**
     * Create an instance of {@link TransactionTypeType }
     * 
     */
    public TransactionTypeType createTransactionTypeType() {
        return new TransactionTypeType();
    }

    /**
     * Create an instance of {@link OrganisationTypeType }
     * 
     */
    public OrganisationTypeType createOrganisationTypeType() {
        return new OrganisationTypeType();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeType }
     * 
     */
    public MessageInTransactionTypeType createMessageInTransactionTypeType() {
        return new MessageInTransactionTypeType();
    }

    /**
     * Create an instance of {@link MessageInTransactionTypeType.Group }
     * 
     */
    public MessageInTransactionTypeType.Group createMessageInTransactionTypeTypeGroup() {
        return new MessageInTransactionTypeType.Group();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "TransactionTypeRef")
    public JAXBElement<TransactionTypeTypeRef> createTransactionTypeRef(TransactionTypeTypeRef value) {
        return new JAXBElement<TransactionTypeTypeRef>(_TransactionTypeRef_QNAME, TransactionTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageInTransactionTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "MessageInTransactionType")
    public JAXBElement<MessageInTransactionTypeType> createMessageInTransactionType(MessageInTransactionTypeType value) {
        return new JAXBElement<MessageInTransactionTypeType>(_MessageInTransactionType_QNAME, MessageInTransactionTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "ProjectType")
    public JAXBElement<ProjectTypeType> createProjectType(ProjectTypeType value) {
        return new JAXBElement<ProjectTypeType>(_ProjectType_QNAME, ProjectTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElementTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "SimpleElementType")
    public JAXBElement<SimpleElementTypeType> createSimpleElementType(SimpleElementTypeType value) {
        return new JAXBElement<SimpleElementTypeType>(_SimpleElementType_QNAME, SimpleElementTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexElementTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "ComplexElementTypeRef")
    public JAXBElement<ComplexElementTypeTypeRef> createComplexElementTypeRef(ComplexElementTypeTypeRef value) {
        return new JAXBElement<ComplexElementTypeTypeRef>(_ComplexElementTypeRef_QNAME, ComplexElementTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "PersonType")
    public JAXBElement<PersonTypeType> createPersonType(PersonTypeType value) {
        return new JAXBElement<PersonTypeType>(_PersonType_QNAME, PersonTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoleTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "RoleTypeRef")
    public JAXBElement<RoleTypeTypeRef> createRoleTypeRef(RoleTypeTypeRef value) {
        return new JAXBElement<RoleTypeTypeRef>(_RoleTypeRef_QNAME, RoleTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "PersonTypeRef")
    public JAXBElement<PersonTypeTypeRef> createPersonTypeRef(PersonTypeTypeRef value) {
        return new JAXBElement<PersonTypeTypeRef>(_PersonTypeRef_QNAME, PersonTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AppendixTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "AppendixType")
    public JAXBElement<AppendixTypeType> createAppendixType(AppendixTypeType value) {
        return new JAXBElement<AppendixTypeType>(_AppendixType_QNAME, AppendixTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "TransactionType")
    public JAXBElement<TransactionTypeType> createTransactionType(TransactionTypeType value) {
        return new JAXBElement<TransactionTypeType>(_TransactionType_QNAME, TransactionTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementConditionTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "ElementConditionRef")
    public JAXBElement<ElementConditionTypeRef> createElementConditionRef(ElementConditionTypeRef value) {
        return new JAXBElement<ElementConditionTypeRef>(_ElementConditionRef_QNAME, ElementConditionTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserDefinedTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "UserDefinedTypeRef")
    public JAXBElement<UserDefinedTypeTypeRef> createUserDefinedTypeRef(UserDefinedTypeTypeRef value) {
        return new JAXBElement<UserDefinedTypeTypeRef>(_UserDefinedTypeRef_QNAME, UserDefinedTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserDefinedTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "UserDefinedType")
    public JAXBElement<UserDefinedTypeType> createUserDefinedType(UserDefinedTypeType value) {
        return new JAXBElement<UserDefinedTypeType>(_UserDefinedType_QNAME, UserDefinedTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "GroupType")
    public JAXBElement<GroupTypeType> createGroupType(GroupTypeType value) {
        return new JAXBElement<GroupTypeType>(_GroupType_QNAME, GroupTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "ProjectTypeRef")
    public JAXBElement<ProjectTypeTypeRef> createProjectTypeRef(ProjectTypeTypeRef value) {
        return new JAXBElement<ProjectTypeTypeRef>(_ProjectTypeRef_QNAME, ProjectTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageInTransactionTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "MessageInTransactionTypeRef")
    public JAXBElement<MessageInTransactionTypeTypeRef> createMessageInTransactionTypeRef(MessageInTransactionTypeTypeRef value) {
        return new JAXBElement<MessageInTransactionTypeTypeRef>(_MessageInTransactionTypeRef_QNAME, MessageInTransactionTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElementTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "SimpleElementTypeRef")
    public JAXBElement<SimpleElementTypeTypeRef> createSimpleElementTypeRef(SimpleElementTypeTypeRef value) {
        return new JAXBElement<SimpleElementTypeTypeRef>(_SimpleElementTypeRef_QNAME, SimpleElementTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "MessageType")
    public JAXBElement<MessageTypeType> createMessageType(MessageTypeType value) {
        return new JAXBElement<MessageTypeType>(_MessageType_QNAME, MessageTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AppendixTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "AppendixTypeRef")
    public JAXBElement<AppendixTypeTypeRef> createAppendixTypeRef(AppendixTypeTypeRef value) {
        return new JAXBElement<AppendixTypeTypeRef>(_AppendixTypeRef_QNAME, AppendixTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoleTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "RoleType")
    public JAXBElement<RoleTypeType> createRoleType(RoleTypeType value) {
        return new JAXBElement<RoleTypeType>(_RoleType_QNAME, RoleTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexElementTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "ComplexElementType")
    public JAXBElement<ComplexElementTypeType> createComplexElementType(ComplexElementTypeType value) {
        return new JAXBElement<ComplexElementTypeType>(_ComplexElementType_QNAME, ComplexElementTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "ElementCondition")
    public JAXBElement<ElementConditionType> createElementCondition(ElementConditionType value) {
        return new JAXBElement<ElementConditionType>(_ElementCondition_QNAME, ElementConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "GroupTypeRef")
    public JAXBElement<GroupTypeTypeRef> createGroupTypeRef(GroupTypeTypeRef value) {
        return new JAXBElement<GroupTypeTypeRef>(_GroupTypeRef_QNAME, GroupTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionPhaseTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "TransactionPhaseTypeRef")
    public JAXBElement<TransactionPhaseTypeTypeRef> createTransactionPhaseTypeRef(TransactionPhaseTypeTypeRef value) {
        return new JAXBElement<TransactionPhaseTypeTypeRef>(_TransactionPhaseTypeRef_QNAME, TransactionPhaseTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "MessageTypeRef")
    public JAXBElement<MessageTypeTypeRef> createMessageTypeRef(MessageTypeTypeRef value) {
        return new JAXBElement<MessageTypeTypeRef>(_MessageTypeRef_QNAME, MessageTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionPhaseTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "TransactionPhaseType")
    public JAXBElement<TransactionPhaseTypeType> createTransactionPhaseType(TransactionPhaseTypeType value) {
        return new JAXBElement<TransactionPhaseTypeType>(_TransactionPhaseType_QNAME, TransactionPhaseTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationTypeTypeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "OrganisationTypeRef")
    public JAXBElement<OrganisationTypeTypeRef> createOrganisationTypeRef(OrganisationTypeTypeRef value) {
        return new JAXBElement<OrganisationTypeTypeRef>(_OrganisationTypeRef_QNAME, OrganisationTypeTypeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", name = "OrganisationType")
    public JAXBElement<OrganisationTypeType> createOrganisationType(OrganisationTypeType value) {
        return new JAXBElement<OrganisationTypeType>(_OrganisationType_QNAME, OrganisationTypeType.class, null, value);
    }

}
