//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.25 at 11:50:28 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ISO29481_Part_2A.com/schemas/20110819", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.iso29481_part_2a.schemas._20110819;
