//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.25 at 11:50:28 AM CEST 
//


package com.iso29481_part_2a.schemas._20110819;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SimpleElementTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleElementTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ISO29481_Part_2A.com/schemas/20110819}elementType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="interfaceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateLaMu" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="userLaMu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="helpInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="valueList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userDefinedType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}UserDefinedType"/>
 *                   &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}UserDefinedTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleElementTypeType", propOrder = {
    "description",
    "interfaceType",
    "state",
    "dateLaMu",
    "userLaMu",
    "language",
    "category",
    "helpInfo",
    "valueList",
    "userDefinedType"
})
public class SimpleElementTypeType
    extends ElementType
{

    @XmlElement(required = true)
    protected String description;
    protected String interfaceType;
    protected String state;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateLaMu;
    protected String userLaMu;
    protected String language;
    protected String category;
    protected String helpInfo;
    protected String valueList;
    @XmlElement(required = true)
    protected SimpleElementTypeType.UserDefinedType userDefinedType;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the interfaceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * Sets the value of the interfaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceType(String value) {
        this.interfaceType = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the dateLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLaMu() {
        return dateLaMu;
    }

    /**
     * Sets the value of the dateLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLaMu(XMLGregorianCalendar value) {
        this.dateLaMu = value;
    }

    /**
     * Gets the value of the userLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLaMu() {
        return userLaMu;
    }

    /**
     * Sets the value of the userLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLaMu(String value) {
        this.userLaMu = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the helpInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpInfo() {
        return helpInfo;
    }

    /**
     * Sets the value of the helpInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpInfo(String value) {
        this.helpInfo = value;
    }

    /**
     * Gets the value of the valueList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueList() {
        return valueList;
    }

    /**
     * Sets the value of the valueList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueList(String value) {
        this.valueList = value;
    }

    /**
     * Gets the value of the userDefinedType property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleElementTypeType.UserDefinedType }
     *     
     */
    public SimpleElementTypeType.UserDefinedType getUserDefinedType() {
        return userDefinedType;
    }

    /**
     * Sets the value of the userDefinedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleElementTypeType.UserDefinedType }
     *     
     */
    public void setUserDefinedType(SimpleElementTypeType.UserDefinedType value) {
        this.userDefinedType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}UserDefinedType"/>
     *         &lt;element ref="{http://www.ISO29481_Part_2A.com/schemas/20110819}UserDefinedTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userDefinedType",
        "userDefinedTypeRef"
    })
    public static class UserDefinedType {

        @XmlElement(name = "UserDefinedType")
        protected UserDefinedTypeType userDefinedType;
        @XmlElement(name = "UserDefinedTypeRef")
        protected UserDefinedTypeTypeRef userDefinedTypeRef;

        /**
         * Gets the value of the userDefinedType property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedTypeType }
         *     
         */
        public UserDefinedTypeType getUserDefinedType() {
            return userDefinedType;
        }

        /**
         * Sets the value of the userDefinedType property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedTypeType }
         *     
         */
        public void setUserDefinedType(UserDefinedTypeType value) {
            this.userDefinedType = value;
        }

        /**
         * Gets the value of the userDefinedTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link UserDefinedTypeTypeRef }
         *     
         */
        public UserDefinedTypeTypeRef getUserDefinedTypeRef() {
            return userDefinedTypeRef;
        }

        /**
         * Sets the value of the userDefinedTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link UserDefinedTypeTypeRef }
         *     
         */
        public void setUserDefinedTypeRef(UserDefinedTypeTypeRef value) {
            this.userDefinedTypeRef = value;
        }

    }

}
